name: Fetch_Comment

on:
  schedule:
    - cron: "*/2 * * * *" # 每2分钟执行一次
  workflow_dispatch:

jobs:
  fetch_news:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm run start
      - name: Display current time
        run: date +%Y-%m-%d\ %H:%M:%S
      - name: Format code with Prettier
        run: npm run prettier
      - name: Commit and push changes
        run: |
          git config --local user.email "exposir@foxmail.com"
          git config --local user.name "exposir"
          git pull
          git add .
          git status
          git commit -m "Update Comment - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: main
