name: Fetch_Comment

on:
  schedule:
    - cron: "*/2 * * * *" # 每2分钟执行一次
  workflow_dispatch:

jobs:
  fetch_news:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm run start
      - name: Display current time
        run: date +%Y-%m-%d\ %H:%M:%S
      - name: Format code with Prettier for staged files only
        run: |
          git add .
          git diff --name-only --staged --diff-filter=d | xargs -I {} npx prettier --write {} || true
      - name: Commit and push changes
        run: |
          git config --local user.email "exposir@foxmail.com"
          git config --local user.name "exposir"
          git pull
          git add -u
          git status
          git commit -m "Update Comment - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: main
